<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UCSeeder extends Seeder
{
    private static $counter = 1;
    protected array $tehsils = [
        'Hub',
        'Gaddani',
        'Sonmiani',
        'Sakran',
        'Dureji',
        'Kalat',
        'Mangochar',
        'Gazg',
        'Johan',
        'Khuzdar',
        'Nall',
        'Wadh',
        'Zehri',
        'Dasht Mastung',
        'Mastung',
        'Khad Koocha',
        'Kardigap',
        'Surab',
        'Ziarat',
        'Sinjavi',
        'Gwadar',
        'Jiwani',
        'Ormara',
        'Pasni',
        'Suntsar',
        'Mand',
        'Tump',
        'Turbat',
        'Gowargo',
        'Panjgur',
        'Paroom',
        'Gichk',
        'Jafarabad',
        'Jhatpat',
        'Baba Kot',
        'Dera Murad Jamali',
        'Tamboo',
        'Chattar',
        'Meer Hassan',
        'Faridabad',
        'Hayrvi',
        'Manjipur',
        'Sohbatpur',
        'Dhadar',
        'Balanari',
        'Khattan',
        'Mach',
        'Sani',
        'Gandawa',
        'Jhal Magsi',
        'Mirpur',
        'Chaman',
        'Barshore',
        'Hurramzai',
        'Pishin',
        'Saranan',
        'Chiltan',
        'Zarghoon',
        'Panjpai',
        'Sadar',
        'Gulistan',
        'Killa Abdullah',
        'Dobandi',
        'Dera Bugti',
        'Phelawagh',
        'Sui',
        'Baiker',
        'Sibi',
        'Kutmandai',
        'Sangan',
        'Kahan',
        'Kohlu',
        'Maiwand',
        'Shaheed Jahangir Abad',
        'Harnai',
        'Shahrig',
        'Khoast',
        'Killa Saifullah',
        'Loiband',
        'Muslim Bagh',
        'Badini',
        'Kanmetharzai',
        'Shinki',
        'Sherani',
        'Qamar Din Karez',
        'Zhob',
        'Ashwat',
        'Kashatu',
        'Sambaza',
        'Duki',
        'Darug',
        'Kingri',
        'Musakhel',
        'Toisar',
        'Bori',
        'Mekhtar',
        'Barkhan',
        'Dalbandin',
        'Nokundi',
        'Taftan',
        'Chagai',
        'Amuri',
        'Chilgazi',
        'Besima',
        'Mashkel',
        'Washuk',
        'Nag',
        'Shahgori',
        'Nushki',
        'Dak',
        'Kharan',
        'Sar-Kharan',
        'Tohumulk',
        'Bahawalnagar',
        'Chishtian',
        'Fort Abbas',
        'Haroonabad',
        'Minchinabad',
        'Ahmadpur East',
        'Bahawalpur City',
        'Bahawalpur Saddar',
        'Hasilpur',
        'Khairpur Tamewali',
        'Yazman',
        'Khanpur',
        'Liaqatpur',
        'Rahim Yar Khan',
        'Sadiqabad',
        'Dera Ghazi Khan',
        'De-Excluded Area D.G. Khan',
        'Kot Chutta',
        'Jampur',
        'Muhammadpur',
        'Dajal',
        'Tribal Area',
        'Chaubara',
        'Karor Lal Esan',
        'Layyah',
        'Alipur',
        'Jatoi',
        'Muzaffargarh',
        'Rajanpur',
        'Rojhan',
        'De-Excluded Area Rajanpur',
        'Taunsa',
        'Koh-e-Suleman',
        'Vehova',
        'Kot Addu',
        'Chowk Sarwar Shaheed',
        'Bhowana',
        'Chiniot',
        'Lalian',
        'Chak Jhumra',
        'Faisalabad City',
        'Faisalabad Sadar',
        'Jhang',
        'Shorkot',
        'Ahmadpur Sial',
        'Athara Hazari',
        'Mandi Shah Jeewna',
        'Gojra',
        'Kamalia',
        'Pirmahal',
        'Toba Tek Singh',
        'Gujranwala City',
        'Gujranwala Saddar',
        'Kamoke',
        'Nowshera Virkan',
        'Narowal',
        'Shakargarh',
        'Zafarwal',
        'Daska',
        'Pasrur',
        'Sambrial',
        'Sialkot',
        'Gujrat',
        'Kharian',
        'Sarai Alamgir',
        'Jalalpur Jattan',
        'Kunjah',
        'Hafizabad',
        'Pindi Bhattian',
        'Malakwal',
        'Mandi Bahauddin',
        'Phalia',
        'Wazirabad',
        'Ali Pur Chatta',
        'Chunian',
        'Kasur',
        'Kot Radha Kishan',
        'Pattoki',
        'Lahore Cantonment',
        'Lahore City',
        'Model Town',
        'Raiwind',
        'Nankana Sahib',
        'Sangla Hill',
        'Shah Kot',
        'Sheikhupura',
        'Sharak Pur',
        'Jahanian',
        'Kabirwala',
        'Khanewal',
        'Mian Channu',
        'Dunyapur',
        'Kahror Pacca',
        'Lodhran',
        'Jalalpur Pirwala',
        'Multan City',
        'Multan Saddar',
        'Shujabad',
        'Jallah Jeem'
        ,
        'Burewala',
        'Mailsi',
        'Vehari',
        'Attock',
        'Fateh Jang',
        'Hassan Abdal',
        'Hazro',
        'Chakwal',
        'Choa Saidan Shah',
        'Kallar Kahar',
        'Dina',
        'Jhelum',
        'Pind Dadan Khan',
        'Sohawa',
        'Rawalpindi',
        'Gujar Khan',
        'Kahuta',
        'Kallar Syedan',
        'Taxila',
        'Kotli Sattian',
        'Murree',
        'Depalpur',
        'Okara',
        'Renala Khurd',
        'Chichawatni',
        'Sahiwal',
        'Khushab',
        'Noorpur Thal',
        'Quaidabad',
        'Naushera (Wadi-e-Soon)',
        'Sargodha'
        ,
        'Bhakkar',
        'Darya Khan',
        'Kaloorkot',
        'Mankera',
        'Isakhel',
        'Mianwali',
        'Piplan',
        'Talagang',
        'Lawa',
        'Multan Khurd',
        'Bannu',
        'Kakki',
        'Wazir',
        'Bettani',
        'Ghazni Khel',
        'Lakki Marwat',
        'Sari Naurang',
        'Ghulam Khan',
        'Mir Ali',
        'Miran Shah',
        'Daraban',
        'Darazinda',
        'Dera Ismail Khan',
        'Jandola',
        'Tank',
        'Hazara',
        'Ladha',
        'Makin',
        'Sararogha',
        'Birmil',
        'Shakai',
        'Toi Khulla',
        'Wana',
        'Abbottabad',
        'Havelian',
        'Lora',
        'Lower Tanawal',
        'Allai',
        'Batagram',
        'Ghazi',
        'Haripur',
        'Kolai-Palas',
        'Kolai',
        'Palas',
        'Bankad',
        'Pattan',
        'Baffa Pakhal',
        'Bala Kot',
        'Mansehra'
        ,
        'Daur Maira',
        'Judba',
        'Khander Hassanzai',
        'Dassu',
        'Harban Basha',
        'Kandia',
        'Seo',
        'Doaba',
        'Hangu',
        'Tall',
        'Banda Daud Shah',
        'Karak',
        'Takht-e-Nasrati',
        'Dara Adam Khel',
        'Gumbat',
        'Kohat',
        'Lachi',
        'Central Kurram',
        'Lower Kurram',
        'Upper Kurram',
        'Central Orakzai',
        'Ismail Zai',
        'Lower Orakzai',
        'Upper Orakzai',
        'Bar Chamarkand',
        'Barang',
        'Khar Bajaur',
        'Utman Khel',
        'Chagharzai',
        'Daggar',
        'Gadezai',
        'Khudu Khel',
        'Mandanr',
        'Chitral',
        'Drosh',
        'Adenzai',
        'Balambat',
        'Samar Bagh',
        'Timergara',
        'Sam Ranizai',
        'Swat Ranizai',
        'Thana Baizai',
        'Alpuri',
        'Bisham',
        'Chakesar',
        'Martung',
        'Makhuzai',
        'Puran',
        'Babuzai'
        ,
        'Barikot',
        'Behrain',
        'Charbagh',
        'Kabal',
        'Khwaza Khela',
        'Matta',
        'Buni',
        'Mulkhow',
        'Torkhow',
        'Mastuj',
        'Barawal',
        'Dir',
        'Kalkot',
        'Lar Jam',
        'Sharingal',
        'Wari',
        'Charsadda',
        'Shabqadar',
        'Tangi',
        'Ghari Kapura',
        'Katlang',
        'Mardan',
        'Rustam',
        'Takht Bhai',
        'Lahor',
        'Razar',
        'Swabi',
        'Topi',
        'Bagh Maidan',
        'Bara'
        ,
        'Bazar Zakha Khel',
        'Fort Salop',
        'Jamrud',
        'Landi Kotal',
        'Mula Gori',
        'Painda Cheena',
        'Ambar Utman Khel',
        'Halim Zai',
        'Pindiali',
        'Pran Ghar',
        'Safi',
        'Upper Mohmand',
        'Yake Ghund',
        'Jehangira',
        'Nowshera',
        'Pabbi',
        'Badbher',
        'Chamkani',
        'Hassan Khel',
        'Mathra',
        'Peshawar City',
        'Peshtakhara',
        'Shah Alam',
        'Punial',
        'Ishkoman',
        'Danyor',
        'Gilgit',
        'Juglot',
        'Aliabad',
        'Gojal',
        'Nagar',
        'Chalt',
        'Gultari',
        'Skardu',
        'Gamba',
        'Rondu',
        'Kharmang',
        'Astore',
        'Shounter',
        'Babusar',
        'Chilas',
        'Dadyal',
        'Islamgarh',
        'Bhimber',
        'Barnala',
        'Samahni',
        'Kotli',
        'Khuiratta',
        'Fatehpur Thakiala',
        'Muzaffarabad',
        'Nasirbad',
        'Hattian Bala',
        'Chikkar',
        'Leepa',
        'Athmuqam',
        'Sharda',
        'Bagh',
        'Dhirkot',
        'Haveli',
        'Khurshidabad',
        'Mumtazabad',
        'Badin',
        'Khoski',
        'Matli',
        'Jati',
        'Kharo Chan',
        'Mirpur Bathoro',
        'Shah Bandar',
        'Sujawal',
        'Ghorabari',
        'Keti Bunder',
        'Mirpur Sakro',
        'Thatta',
        'Dadu',
        'Johi',
        'Khairpur Nathan Shah',
        'Mehar',
        'Hyderabad City',
        'Hyderabad',
        'Latifabad',
        'Qasimabad',
        'Kotri',
        'Sehwan',
        'Manjhand',
        'Thana Bulla Khan',
        'Hala',
        'Matiari',
        'Saeedabad',
        'Chamber',
        'Jhando Mari',
        'Tando Allahyar',
        'Nasarpur',
        'Bulri Shah Karim',
        'Tando Ghulam Hyder',
        'Tando Mohammad Khan',
        'Gulberg Town',
        'Liaquatabad Town',
        'New Karachi Town',
        'North Nazimabad Town',
        'Nazimabad',
        'North Karachi',
        'Gulistan-e-Jouhar',
        'Gulshan Town',
        'Jamshed Town',
        'Ferozabad',
        'Gulshan-E-Iqbal',
        'Gulzar-E-Hijri',
        'Lyari Town',
        'Saddar Town',
        'Aram Bagh',
        'Civil Line',
        'Garden',
        'Orangi Town',
        'Manghopir',
        'Maripur',
        'Mominabad',
        'Ittehad town',
        'Baldia town',
        'Korangi Town',
        'Landhi Town',
        'Shah Faisal Town',
        'Model Colony',
        'Keamari Town',
        'Baldia Town',
        'S.I.T.E. Town',
        'Karachi Fish Harbour',
        'Bin Qasim Town',
        'Gadap Town',
        'Malir Town',
        'Jinnah',
        'Ibrahim Hyderi',
        'Murad Memon',
        'Shah Murad',
        'New Sukkur',
        'Pano Aqil',
        'Rohri',
        'Salehpat',
        'Sukkur',
        'Garhi Khairo',
        'Jacobabad',
        'Thul',
        'Kandhkot',
        'Kashmore',
        'Tangwani',
        'Bakrani',
        'Dokri'
        ,
        'Larkana',
        'Ratodero',
        'Mirokhan',
        'Shahdadkot',
        'Sijawal Junejo'
        ,
        'Warah'
        ,
        'Garhi Yasin',
        'Lakhi',
        'Shikarpur',
        'Mirpur Khas',
        'Sindhri',
        'Jam Nawaz Ali',
        'Khipro',
        'Sanghar',
        'Shahdadpur',
        'Sinjhoro',
        'Tando Adam Khan'
    ];
    
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        call_user_func([$this, 'getCapitalUC'], 5);

        foreach ($this->tehsils as $tehsil) {
            \App\Models\UnionCouncil::create([
                'name' => $this->generate('name'),
                'code' => $this->generate('code'),
                'tehsil_id' => $this->getParentId($tehsil)
            ]);
        }
    }

    private function getCapitalUC(int $uc) {
        while($uc > 0) {
            \App\Models\UnionCouncil::create([
                'name' => $this->generate('name'),
                'code' => $this->generate('code'),
                'province_id' => $this->getParentId('Islamabad')
            ]);
            $uc--;
        }
    }

    private function generate(string $type) {
        if($type == 'name') {
            return sprintf('Union Council %s', self::$counter);
        }
        // self::$counter++;
        return sprintf('UC %s', self::$counter++);
    }
    private function getParentId(string $name) {
        if($name == 'Islamabad') {
            return \App\Models\Province::where('name', '=', $name)->first()->getAttribute('id');
        }
        if(\App\Models\Tehsil::where('name', '=', $name)->first()) {
            return \App\Models\Tehsil::where('name', '=', $name)->first()->getAttribute('id');
        }
        return \App\Models\Tehsil::first()->getAttribute('id');
    }
}
